### ISSUE TITLE
webpack.config.production.js not found

### ISSUE THREAD

**Issue by roth1002** [chentsulin/generator-redux-app#1]
module.js:334
    throw err;
          ^
Error: Cannot find module '/Users/pengyuzhao/Study/react/webpack.config.production.js'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at module.exports (/Users/pengyuzhao/Study/react/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/pengyuzhao/Study/react/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)

**Comment by roth1002** [comment]
$ yo redux-app
? What do you want to name your app? react-dnd-roth
? What is your GitHub username? roth1002
? What is the URL of your website? http://github.com/roth1002
? Do you need to use flow type? Yes
   create package.json
   create .editorconfig
   create .gitattributes
   create .gitignore
   create .eslintrc
   create .travis.yml
   create index.html
   create server.js
   create webpack.config.js
   create LICENSE
   create CHANGELOG.md
   create README.md
   create .babelrc
   create .flowconfig
   create src/actions/counter.js
   create src/components/Counter.js
   create src/components/Main.js
   create src/containers/App.js
   create src/containers/CounterPage.js
   create src/containers/Root.js
   create src/containers/index.js
   create src/index.js
   create src/reducers/counter.js
   create src/reducers/index.js
   create src/routes.js
   create src/store/configureStore.js
   create src/utils/.gitkeep
   create test/actions/counter.spec.js
   create test/components/Counter.spec.js
   create test/containers/CounterPage.spec.js
   create test/reducers/counter.spec.js


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

**Comment by chentsulin** [comment]
should be fixed in v0.3.4.
